name: Build Android Dynamic Library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25

      - name: Build
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          ls -l $ANDROID_HOME
          ls -l $ANDROID_HOME/ndk
          export NDK_VERSION=r25
          export ANDROID_NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION
          export PATH=$PATH:$ANDROID_NDK_HOME
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang++
          export CGO_ENABLED=1
          export GOOS=android
          export GOARCH=arm64
          export GO111MODULE=on
          go build -buildmode=c-shared -ldflags="-s -w" -v -o goapplib.android.arm64.so ./cmd/cgo/main.go

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: goapplib
          path: goapplib.android.arm64.so
