name: Build Android Dynamic Library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
        id: go

      - name: Set up Android NDK
        uses: r0adkll/setup-android-ndk@v1
        with:
          version: 'r21'

      - name: Build
        run: |
          export ANDROID_NDK_HOME=$RUNNER_WORKSPACE/android-ndk-r21
          export PATH=$PATH:$ANDROID_NDK_HOME
          export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
          export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
          export CGO_ENABLED=1
          export GOOS=android
          export GOARCH=arm64
          export GOARM=7
          export GO111MODULE=on
          go build -buildmode=c-shared -ldflags="-s -w" -o goapplib.android.arm64.so .

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: goapplib
          path: goapplib.android.arm64.so
