name: Build Android Dynamic Library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
        id: go

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25

      - name: Build
        run: |
          go env
          export CGO_ENABLED=1
          go build -buildmode=c-shared -ldflags="-s -w" -o goapplib.linux.x86_64.so ./cmd/cgo/main.go
          

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: goapplib
          path: |
              goapplib.linux.x86_64.so
